'use client';

import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { supabase } from '@/lib/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { CreditCard, CalendarDays, Receipt } from 'lucide-react';

type Sub={status:string;billing_cycle:string;start_date:string;end_date:string|null;subscription_plans?:{name:string;currency:string}|null};
type Invoice={id:string;invoice_number:string;amount:number;currency:string;status:string;billing_period_start:string|null;billing_period_end:string|null;paid_at:string|null;created_at:string};
type ReceiptRow={id:string;receipt_number:string;amount:number;currency:string;issued_at:string;payload:any};

export default function BillingPage(){
 const {activeBusiness}=useAuth(); const [sub,setSub]=useState<Sub|null>(null); const [invoices,setInvoices]=useState<Invoice[]>([]); const [receipts,setReceipts]=useState<ReceiptRow[]>([]); const [from,setFrom]=useState(''); const [to,setTo]=useState('');
 const load=async()=>{if(!activeBusiness)return;const [s,i,r]=await Promise.all([supabase.from('business_subscriptions').select('status,billing_cycle,start_date,end_date,subscription_plans(name,currency)').eq('business_id',activeBusiness.id).maybeSingle(),supabase.from('subscription_invoices').select('*').eq('business_id',activeBusiness.id).order('created_at',{ascending:false}),supabase.from('payment_receipts').select('*').eq('business_id',activeBusiness.id).eq('channel','subscription').order('issued_at',{ascending:false})]);setSub(s.data as any);setInvoices((i.data||[]) as Invoice[]);setReceipts((r.data||[]) as ReceiptRow[]);};
 useEffect(()=>{load();},[activeBusiness]);
 const filtered=useMemo(()=>invoices.filter(i=>(!from||i.created_at>=from)&&(!to||i.created_at<=to+'T23:59:59')), [invoices,from,to]);
 const daysLeft=sub?.end_date?Math.ceil((new Date(sub.end_date).getTime()-Date.now())/86400000):null;
 return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CreditCard className="h-4 w-4"/>Current Plan</CardTitle></CardHeader><CardContent><div className="text-xl font-bold">{sub?.subscription_plans?.name||'No active plan'}</div><Badge className="mt-2">{sub?.status||'inactive'}</Badge><p className="mt-3 text-sm text-muted-foreground">{sub?.billing_cycle||'-'} billing</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-4 w-4"/>Plan Expiry</CardTitle></CardHeader><CardContent><div className="text-xl font-bold">{sub?.end_date?new Date(sub.end_date).toLocaleDateString():'-'}</div><p className="mt-2 text-sm text-muted-foreground">{daysLeft==null?'No expiry recorded':daysLeft>=0?daysLeft+' days remaining':'Expired'}</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Receipt className="h-4 w-4"/>Payment History</CardTitle></CardHeader><CardContent><div className="text-xl font-bold">{invoices.filter(i=>i.status==='paid').length}</div><p className="mt-2 text-sm text-muted-foreground">Paid subscription bills</p></CardContent></Card></div>
 <Card><CardHeader><CardTitle>Monthly Billing & Payment Status</CardTitle><div className="flex gap-3"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></CardHeader><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Invoice</th><th className="p-3">Period</th><th className="p-3">Amount</th><th className="p-3">Paid</th><th className="p-3">Status</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id} className="border-b"><td className="p-3 font-medium">{i.invoice_number}</td><td className="p-3">{i.billing_period_start?new Date(i.billing_period_start).toLocaleDateString():'-'} → {i.billing_period_end?new Date(i.billing_period_end).toLocaleDateString():'-'}</td><td className="p-3">{i.currency} {Number(i.amount).toLocaleString()}</td><td className="p-3">{i.paid_at?new Date(i.paid_at).toLocaleDateString():'-'}</td><td className="p-3"><Badge>{i.status}</Badge></td></tr>)}</tbody></table>{!filtered.length&&<div className="py-12 text-center text-muted-foreground">No billing records in the selected date range.</div>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Payment Slips / Receipts</CardTitle></CardHeader><CardContent className="space-y-3">{receipts.map(r=><div key={r.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{r.receipt_number}</p><p className="text-sm text-muted-foreground">{new Date(r.issued_at).toLocaleString()}</p></div><strong>{r.currency} {Number(r.amount).toLocaleString()}</strong></div>)}{!receipts.length&&<p className="text-sm text-muted-foreground">Payment slips will appear here after your subscription payment is approved.</p>}</CardContent></Card></div>;
}