'use client';

import { useEffect, useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { supabase } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { CheckCircle2, Plus, Receipt } from 'lucide-react';

type Order={id:string;order_number:string;customer_name:string|null;currency:string;balance_due:number};
type Payment={id:string;order_id:string|null;payer_name:string|null;payer_contact:string|null;amount:number;currency:string;payment_method:string|null;payment_reference:string|null;status:string;created_at:string;orders?:Order|null};

export default function CustomerPaymentsPage(){
 const {activeBusiness,profile}=useAuth(); const [payments,setPayments]=useState<Payment[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [open,setOpen]=useState(false);
 const [form,setForm]=useState({order_id:'',payer_name:'',payer_contact:'',amount:'',currency:'PKR',payment_method:'bank_transfer',payment_reference:'',channel:'manual'});
 const load=async()=>{if(!activeBusiness)return;const [p,o]=await Promise.all([supabase.from('customer_payments').select('*,orders(id,order_number,customer_name,currency,balance_due)').eq('business_id',activeBusiness.id).order('created_at',{ascending:false}),supabase.from('orders').select('id,order_number,customer_name,currency,balance_due').eq('business_id',activeBusiness.id).in('status',['inquiry','quotation_sent','awaiting_payment','confirmed','processing'])]);setPayments((p.data||[]) as Payment[]);setOrders((o.data||[]) as Order[]);};
 useEffect(()=>{load();},[activeBusiness]);
 const save=async()=>{if(!activeBusiness||!form.amount)return;const order=orders.find(x=>x.id===form.order_id);await supabase.from('customer_payments').insert({business_id:activeBusiness.id,order_id:form.order_id||null,payer_name:form.payer_name||order?.customer_name||null,payer_contact:form.payer_contact||null,amount:Number(form.amount),currency:form.currency||order?.currency||'PKR',payment_method:form.payment_method,payment_reference:form.payment_reference||null,channel:form.channel,status:'pending_review'});setOpen(false);load();};
 const approve=async(p:Payment)=>{await supabase.from('customer_payments').update({status:'approved',approved_at:new Date().toISOString(),approved_by:profile?.id||null}).eq('id',p.id);load();};
 const reject=async(id:string)=>{await supabase.from('customer_payments').update({status:'rejected'}).eq('id',id);load();};
 return <div className="space-y-6"><div className="flex justify-between items-center"><p className="text-muted-foreground">Approve customer advances and full payments. Approval automatically updates the order balance and creates a receipt notification.</p><Button onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4"/>Record Payment</Button></div>
 <Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Customer / Order</th><th className="p-3">Amount</th><th className="p-3">Method / Ref</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{payments.map(p=><tr key={p.id} className="border-b"><td className="p-3">{p.payer_name||'-'}<div className="text-xs text-muted-foreground">{p.orders?.order_number||'No order'} · {p.payer_contact||''}</div></td><td className="p-3 font-medium">{p.currency} {Number(p.amount).toLocaleString()}</td><td className="p-3">{p.payment_method||'-'}<div className="text-xs text-muted-foreground">{p.payment_reference||''}</div></td><td className="p-3"><Badge variant={p.status==='approved'?'default':'secondary'}>{p.status}</Badge></td><td className="p-3 flex gap-2">{p.status==='pending_review'&&<><Button size="sm" onClick={()=>approve(p)}><CheckCircle2 className="mr-1 h-3 w-3"/>Approve</Button><Button size="sm" variant="destructive" onClick={()=>reject(p.id)}>Reject</Button></>}</td></tr>)}</tbody></table>{!payments.length&&<div className="py-14 text-center text-muted-foreground"><Receipt className="mx-auto mb-2 h-8 w-8"/>No customer payments recorded.</div>}</CardContent></Card>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Record Customer Payment</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>Order</Label><select className="w-full rounded border bg-background p-2" value={form.order_id} onChange={e=>{const o=orders.find(x=>x.id===e.target.value);setForm({...form,order_id:e.target.value,currency:o?.currency||form.currency,payer_name:o?.customer_name||form.payer_name,amount:o?String(o.balance_due):form.amount});}}><option value="">Unlinked payment</option>{orders.map(o=><option key={o.id} value={o.id}>{o.order_number} — {o.customer_name} — due {o.currency} {Number(o.balance_due).toLocaleString()}</option>)}</select></div><div><Label>Payer Name</Label><Input value={form.payer_name} onChange={e=>setForm({...form,payer_name:e.target.value})}/></div><div><Label>Payer Contact</Label><Input value={form.payer_contact} onChange={e=>setForm({...form,payer_contact:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><Label>Amount</Label><Input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div><Label>Currency</Label><Input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></div></div><div><Label>Payment Method</Label><Input value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}/></div><div><Label>Reference</Label><Input value={form.payment_reference} onChange={e=>setForm({...form,payment_reference:e.target.value})}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={save}>Submit for Approval</Button></DialogFooter></DialogContent></Dialog></div>;
}