import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'AI Customer Support for Businesses | WhatsApp & Multi-Channel', description: '24/7 AI customer support for WhatsApp, Instagram, Facebook Messenger and website chat. Answer questions, capture leads, book appointments and automate follow-up with AgentHub AI.', alternates: { canonical: '/ai-customer-support' } };

const channels = [['WhatsApp','Handle customer messages, sales questions and voice conversations where many customers already communicate.'],['Instagram','Automate direct-message enquiries while keeping responses grounded in your business information.'],['Facebook Messenger','Respond to customer enquiries and guide prospects toward the configured next action.'],['Website chat','Give website visitors instant answers and capture leads day and night.']];
const workflows = [['Answer','Use your approved business knowledge, products, services, prices and policies.'],['Capture','Collect the customer details needed for sales, support or appointment workflows.'],['Act','Guide customers toward a booking, enquiry, order step or human handoff.'],['Follow up','Reconnect with eligible leads when a conversation becomes inactive.']];

export default function AICustomerSupportPage() { return <main className="min-h-screen bg-[#050816] px-6 py-20 text-white"><article className="mx-auto max-w-4xl"><Link href="/" className="text-sm text-cyan-300">← AgentHub AI</Link><p className="mt-12 text-sm font-semibold uppercase tracking-[.2em] text-violet-300">AI customer support</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">AI customer support for businesses on WhatsApp and beyond</h1><p className="mt-6 text-lg leading-8 text-slate-300">AgentHub AI combines customer support with business automation. It can answer routine questions, use approved products and prices, capture customer information, schedule appointments, follow up with leads and hand conversations to a human whenever required.</p><h2 className="mt-16 text-3xl font-bold">One AI support layer across your channels</h2><div className="mt-8 grid gap-5 sm:grid-cols-2">{channels.map(([t,d])=><section key={t} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="text-xl font-semibold">{t}</h2><p className="mt-3 leading-7 text-slate-400">{d}</p></section>)}</div><h2 className="mt-16 text-3xl font-bold">More than a chatbot: answer, capture, act and follow up</h2><div className="mt-8 grid gap-5 sm:grid-cols-2">{workflows.map(([t,d])=><section key={t} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="text-xl font-semibold">{t}</h2><p className="mt-3 leading-7 text-slate-400">{d}</p></section>)}</div><p className="mt-8 leading-8 text-slate-300">The strongest customer-support automation is grounded in the company's own information and rules. That makes the agent useful for real business conversations while keeping humans responsible for exceptions, sensitive cases and decisions that should not be automated.</p><h2 className="mt-12 text-2xl font-bold">Explore AgentHub resources</h2><div className="mt-5 flex flex-wrap gap-3"><Link href="/blog/whatsapp-ai-automation-guide" className="rounded-xl border border-white/10 px-4 py-2 text-cyan-300">WhatsApp AI automation guide</Link><Link href="/blog/ai-lead-follow-up" className="rounded-xl border border-white/10 px-4 py-2 text-cyan-300">AI lead follow-up</Link><Link href="/blog/ai-appointment-booking" className="rounded-xl border border-white/10 px-4 py-2 text-cyan-300">AI appointment booking</Link></div><div className="mt-10"><Link href="/#pricing" className="inline-flex rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-6 py-3 font-semibold">Explore AgentHub AI</Link></div></article></main>; }
