'use client';

import { useEffect, useState } from 'react';
import { useAuth } from '@/lib/auth-context';
import { supabase } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Plus, ShoppingCart } from 'lucide-react';

type Product={id:string;name:string;price:number|null;currency:string}; type Service={id:string;name:string;price:number|null;currency:string};
type Order={id:string;order_number:string;customer_name:string|null;customer_phone:string|null;status:string;currency:string;total_amount:number;amount_paid:number;balance_due:number;payment_status:string;created_at:string;order_items?:any[]};

export default function OrdersPage(){
 const {activeBusiness}=useAuth(); const [orders,setOrders]=useState<Order[]>([]); const [products,setProducts]=useState<Product[]>([]); const [services,setServices]=useState<Service[]>([]); const [open,setOpen]=useState(false);
 const [form,setForm]=useState({customer_name:'',customer_phone:'',item_type:'product',item_id:'',quantity:'1',currency:'PKR'});
 const load=async()=>{if(!activeBusiness)return; const [o,p,s]=await Promise.all([supabase.from('orders').select('*,order_items(*)').eq('business_id',activeBusiness.id).order('created_at',{ascending:false}),supabase.from('products').select('id,name,price,currency').eq('business_id',activeBusiness.id).eq('status','active'),supabase.from('services').select('id,name,price,currency').eq('business_id',activeBusiness.id).eq('status','active')]);setOrders((o.data||[]) as Order[]);setProducts((p.data||[]) as Product[]);setServices((s.data||[]) as Service[]);};
 useEffect(()=>{load();},[activeBusiness]);
 const create=async()=>{if(!activeBusiness||!form.customer_name||!form.item_id)return;const source=form.item_type==='product'?products:services;const item=source.find(x=>x.id===form.item_id);if(!item)return;const qty=Math.max(1,Number(form.quantity||1));const total=Number(item.price||0)*qty;const num='ORD-'+Date.now().toString().slice(-8);const {data:order,error}=await supabase.from('orders').insert({business_id:activeBusiness.id,order_number:num,customer_name:form.customer_name,customer_phone:form.customer_phone||null,status:'inquiry',currency:item.currency||form.currency,subtotal:total,total_amount:total,balance_due:total,payment_status:'unpaid'}).select('id').single();if(error||!order)return;await supabase.from('order_items').insert({order_id:order.id,product_id:form.item_type==='product'?item.id:null,service_id:form.item_type==='service'?item.id:null,item_name:item.name,item_type:form.item_type,quantity:qty,unit_price:item.price||0,total_price:total});setOpen(false);setForm({customer_name:'',customer_phone:'',item_type:'product',item_id:'',quantity:'1',currency:'PKR'});load();};
 const updateStatus=async(id:string,status:string)=>{await supabase.from('orders').update({status}).eq('id',id);load();};
 return <div className="space-y-6"><div className="flex justify-between items-center"><p className="text-muted-foreground">Record exactly what a customer asked for or booked, with product/service prices and payment balance.</p><Button onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4"/>Create Order</Button></div>
 <Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Order</th><th className="p-3">Customer</th><th className="p-3">Items</th><th className="p-3">Total</th><th className="p-3">Paid / Due</th><th className="p-3">Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b"><td className="p-3 font-medium">{o.order_number}</td><td className="p-3">{o.customer_name}<div className="text-xs text-muted-foreground">{o.customer_phone}</div></td><td className="p-3">{(o.order_items||[]).map((i:any)=>i.item_name+' × '+i.quantity).join(', ')}</td><td className="p-3">{o.currency} {Number(o.total_amount).toLocaleString()}</td><td className="p-3">{o.currency} {Number(o.amount_paid).toLocaleString()} / {Number(o.balance_due).toLocaleString()}</td><td className="p-3"><select className="rounded border bg-background p-1" value={o.status} onChange={e=>updateStatus(o.id,e.target.value)}>{['inquiry','quotation_sent','awaiting_payment','confirmed','processing','shipped','delivered','cancelled'].map(x=><option key={x}>{x}</option>)}</select><div><Badge variant="secondary">{o.payment_status}</Badge></div></td></tr>)}</tbody></table>{!orders.length&&<div className="py-14 text-center text-muted-foreground"><ShoppingCart className="mx-auto mb-2 h-8 w-8"/>No customer orders yet.</div>}</CardContent></Card>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Create Customer Order</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>Customer Name</Label><Input value={form.customer_name} onChange={e=>setForm({...form,customer_name:e.target.value})}/></div><div><Label>Phone / Channel Contact</Label><Input value={form.customer_phone} onChange={e=>setForm({...form,customer_phone:e.target.value})}/></div><div><Label>Item Type</Label><select className="w-full rounded border bg-background p-2" value={form.item_type} onChange={e=>setForm({...form,item_type:e.target.value,item_id:''})}><option value="product">Product</option><option value="service">Service</option></select></div><div><Label>Product / Service</Label><select className="w-full rounded border bg-background p-2" value={form.item_id} onChange={e=>setForm({...form,item_id:e.target.value})}><option value="">Select item</option>{(form.item_type==='product'?products:services).map(i=><option key={i.id} value={i.id}>{i.name} — {i.currency} {Number(i.price||0).toLocaleString()}</option>)}</select></div><div><Label>Quantity</Label><Input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={create}>Create Order</Button></DialogFooter></DialogContent></Dialog></div>;
}