import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'AI Agent for Pharmacies in Pakistan',
  description: 'Automate pharmacy customer support, medicine enquiries, lead follow-up and order conversations on WhatsApp with AgentHub AI.',
  alternates: { canonical: '/ai-for-pharmacies' },
};

export default function PharmaciesPage() {
  return <main className="min-h-screen bg-[#050816] px-6 py-20 text-white"><article className="mx-auto max-w-4xl"><Link href="/" className="text-sm text-cyan-300">← AgentHub AI</Link><p className="mt-12 text-sm font-semibold uppercase tracking-[.2em] text-emerald-300">Pharmacy automation</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">AI agent for pharmacies in Pakistan</h1><p className="mt-6 text-lg leading-8 text-slate-300">Handle routine pharmacy questions on WhatsApp, share approved product and pricing information, capture enquiries and automatically follow up with customers. AgentHub AI keeps conversations moving 24/7 while your team handles requests that need a human.</p><div className="mt-12 grid gap-5 sm:grid-cols-2">{[['Medicine and product enquiries','Answer approved questions using your pharmacy knowledge and product catalogue.'],['WhatsApp order conversations','Guide customers through product enquiries and pass complex requests to your team.'],['Lead follow-up','Automatically reconnect with customers when an enquiry becomes inactive.'],['Human handoff','Escalate sensitive or unclear requests instead of pretending the AI knows the answer.']].map(([t,d])=><section key={t} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><h2 className="text-xl font-semibold">{t}</h2><p className="mt-3 leading-7 text-slate-400">{d}</p></section>)}</div><h2 className="mt-16 text-3xl font-bold">Built for pharmacy customer conversations</h2><p className="mt-5 leading-8 text-slate-300">AgentHub AI can organize customer conversations, answer repetitive questions from approved business information and trigger follow-up workflows. For medical or prescription-related questions, businesses should configure safe escalation rules and keep final clinical decisions with qualified professionals.</p><div className="mt-10"><Link href="/#pricing" className="inline-flex rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-6 py-3 font-semibold">Start with AgentHub AI</Link></div></article></main>;
}
